### ISSUE TITLE
Documentation on getting algebraic architecture terms for neural networks

### ISSUE THREAD

**Issue by akhauriyash** [automl/towards_nas_from_scratch#1]
Hello,

Is there a simply way to get the algebraic architecture terms for a specific neural network architecture?

**Comment by SimonSchrodi** [comment]
Hi,

you can get the the algebraic architecture term as follows: 
```
# this is the syntax tree as string representation following NLTK's style (https://www.nltk.org/howto/tree.html)
id = config.hyperparameters["architecture"].id 

# this transforms the syntax tree representation to the algebraic architecture term
architecture_term = config.hyperparameters["architecture"].unparse_tree(id) 
```
where `config` is the respective search space instance. Note that all of this is part of the [neps project](https://github.com/automl/neps) containing this (and other) implementation of the search space design.
